language: objective-c
osx_image: xcode7.3
rvm: system
install:
  - export GEM_HOME=tmp/ruby/2.0.0
  - export GEM_PATH=${GEM_HOME}
  - export PATH=${GEM_HOME}/bin:${PATH}
  - gem install bundler --no-document
  - bundle install
script:
  - bundle exec rake ci
